### ISSUE TITLE
broken /censor?

### ISSUE THREAD

**Issue by aolko** [thadunge2/AIDungeon#82]
`/censor` fails to pass a check and enable/disable itself
`> /censor off`
```
Traceback (most recent call last):
  File "play.py", line 753, in <module>
    play_aidungeon_2()
  File "play.py", line 412, in play_aidungeon_2
    if not generator.censor:
AttributeError: 'NoneType' object has no attribute 'censor'
```

**Comment by marktaiwan** [comment]
Fixed in 08bfea141d013083f1c7fb002968148cbf3ded31
